image: node:lts

stages:
  - test
#  - review

test:
  stage: test
  script:
    - node -v
    - npm -v
    - npm install
    - npm test

#pages:
#  stage: review
#  script:
#    - mkdir -p public/$CI_ENVIRONMENT_SLUG
#    - echo 'Hello world test' > public/$CI_ENVIRONMENT_SLUG/index.html
#  artifacts:
#    paths:
#      - public
#  environment:
#    name: review/$CI_COMMIT_REF_NAME
#    url: https://$CI_PROJECT_NAMESPACE.gitlab.io/$CI_PROJECT_NAME/$CI_ENVIRONMENT_SLUG
#    on_stop:  stop_review
#  only:
#    - qcweb2-experimental
#
#stop_review:
#  stage: review
#  script:
#    - echo 'Remove review app'
#  variables:
#    GIT_STRATEGY: none
#  when: manual
#  environment:
#    name: review/$CI_COMMIT_REF_NAME
#    action: stop

